Repository kubernetes-csi/driver-registrar, pull requests merged in 2018-09, with the labels that each got.

#46 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#50 Fix golint issue and remove unused constant
  cmd/driver-registrar/main.go
  pkg/connection/connection_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#49 Fix typo
  cmd/driver-registrar/main.go
  pkg/connection/connection.go
Labels: cncf-cla: yes, lgtm, size/XS

#55 Explicit guard against node label update when using kubelet plugin
  cmd/driver-registrar/node_register.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#56 Rename and document new command arguments
  cmd/driver-registrar/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S
