Repository kubernetes-csi/driver-registrar, pull requests merged in 2018-10, with the labels that each got.

#60 Report node update error
  cmd/driver-registrar/node_register.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#63 Set dependency based on a tag kubernetes-1.12.0
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/client-go/Godeps/Godeps.json
  vendor/k8s.io/csi-api/Godeps/Godeps.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#66 Cherry-pick commits including K8S 1.12.0 vendor file changes to release-0.4
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/driver-registrar/node_register.go
  deploy/docker/Dockerfile
  vendor/k8s.io/apimachinery/Godeps/Godeps.json
  vendor/k8s.io/apimachinery/pkg/apis/config/v1alpha1/register.go
  vendor/k8s.io/client-go/.travis.yml
  vendor/k8s.io/client-go/Godeps/Godeps.json
  vendor/k8s.io/client-go/INSTALL.md
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp_test.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/rest/request_test.go
  vendor/k8s.io/csi-api/Godeps/Godeps.json
Labels: approved, cncf-cla: yes, lgtm, size/XL
